// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: homePageImgInfo.proto

package xinli.moho.protocol;

public final class HomePageImgInfo {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Client2ManagementRequest_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Client2ManagementRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Client2ManagementResponse_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Client2ManagementResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\025homePageImgInfo.proto\"6\n\030Client2Manage" +
                        "mentRequest\022\032\n\022AllHomePageImgInfo\030\001 \002(\t\"" +
                        "H\n\031Client2ManagementResponse\022\023\n\013result_c" +
                        "ode\030\001 \002(\005\022\026\n\016result_message\030\002 \002(\tB\025\n\023xin" +
                        "li.moho.protocol"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_Client2ManagementRequest_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_Client2ManagementRequest_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Client2ManagementRequest_descriptor,
                                new String[]{"AllHomePageImgInfo",});
                        internal_static_Client2ManagementResponse_descriptor =
                                getDescriptor().getMessageTypes().get(1);
                        internal_static_Client2ManagementResponse_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Client2ManagementResponse_descriptor,
                                new String[]{"ResultCode", "ResultMessage",});
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner
                );
    }

    private HomePageImgInfo() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface Client2ManagementRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string AllHomePageImgInfo = 1;

        /**
         * <code>required string AllHomePageImgInfo = 1;</code>
         * <p/>
         * <pre>
         * 固定字符串
         * </pre>
         */
        boolean hasAllHomePageImgInfo();

        /**
         * <code>required string AllHomePageImgInfo = 1;</code>
         * <p/>
         * <pre>
         * 固定字符串
         * </pre>
         */
        String getAllHomePageImgInfo();

        /**
         * <code>required string AllHomePageImgInfo = 1;</code>
         * <p/>
         * <pre>
         * 固定字符串
         * </pre>
         */
        com.google.protobuf.ByteString
        getAllHomePageImgInfoBytes();
    }

    public interface Client2ManagementResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int32 result_code = 1;

        /**
         * <code>required int32 result_code = 1;</code>
         */
        boolean hasResultCode();

        /**
         * <code>required int32 result_code = 1;</code>
         */
        int getResultCode();

        // required string result_message = 2;

        /**
         * <code>required string result_message = 2;</code>
         */
        boolean hasResultMessage();

        /**
         * <code>required string result_message = 2;</code>
         */
        String getResultMessage();

        /**
         * <code>required string result_message = 2;</code>
         */
        com.google.protobuf.ByteString
        getResultMessageBytes();
    }

    /**
     * Protobuf type {@code Client2ManagementRequest}
     */
    public static final class Client2ManagementRequest extends
            com.google.protobuf.GeneratedMessage
            implements Client2ManagementRequestOrBuilder {
        // required string AllHomePageImgInfo = 1;
        public static final int ALLHOMEPAGEIMGINFO_FIELD_NUMBER = 1;
        private static final Client2ManagementRequest defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<Client2ManagementRequest> PARSER =
                new com.google.protobuf.AbstractParser<Client2ManagementRequest>() {
                    public Client2ManagementRequest parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Client2ManagementRequest(input, extensionRegistry);
                    }
                };
        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private Object allHomePageImgInfo_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Client2ManagementRequest.newBuilder() to construct.
        private Client2ManagementRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Client2ManagementRequest(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Client2ManagementRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            allHomePageImgInfo_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static Client2ManagementRequest getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return HomePageImgInfo.internal_static_Client2ManagementRequest_descriptor;
        }

        public static Client2ManagementRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Client2ManagementRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Client2ManagementRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Client2ManagementRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Client2ManagementRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Client2ManagementRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Client2ManagementRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static Client2ManagementRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static Client2ManagementRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Client2ManagementRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(Client2ManagementRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Client2ManagementRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return HomePageImgInfo.internal_static_Client2ManagementRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Client2ManagementRequest.class, Builder.class);
        }

        @Override
        public com.google.protobuf.Parser<Client2ManagementRequest> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required string AllHomePageImgInfo = 1;</code>
         * <p/>
         * <pre>
         * 固定字符串
         * </pre>
         */
        public boolean hasAllHomePageImgInfo() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string AllHomePageImgInfo = 1;</code>
         * <p/>
         * <pre>
         * 固定字符串
         * </pre>
         */
        public String getAllHomePageImgInfo() {
            Object ref = allHomePageImgInfo_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    allHomePageImgInfo_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string AllHomePageImgInfo = 1;</code>
         * <p/>
         * <pre>
         * 固定字符串
         * </pre>
         */
        public com.google.protobuf.ByteString
        getAllHomePageImgInfoBytes() {
            Object ref = allHomePageImgInfo_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                allHomePageImgInfo_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            allHomePageImgInfo_ = "";
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasAllHomePageImgInfo()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getAllHomePageImgInfoBytes());
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getAllHomePageImgInfoBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Client2ManagementRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements Client2ManagementRequestOrBuilder {
            private int bitField0_;
            // required string AllHomePageImgInfo = 1;
            private Object allHomePageImgInfo_ = "";

            // Construct using xinli.moho.protocol.HomePageImgInfo.Client2ManagementRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return HomePageImgInfo.internal_static_Client2ManagementRequest_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return HomePageImgInfo.internal_static_Client2ManagementRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Client2ManagementRequest.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                allHomePageImgInfo_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return HomePageImgInfo.internal_static_Client2ManagementRequest_descriptor;
            }

            public Client2ManagementRequest getDefaultInstanceForType() {
                return Client2ManagementRequest.getDefaultInstance();
            }

            public Client2ManagementRequest build() {
                Client2ManagementRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Client2ManagementRequest buildPartial() {
                Client2ManagementRequest result = new Client2ManagementRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.allHomePageImgInfo_ = allHomePageImgInfo_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Client2ManagementRequest) {
                    return mergeFrom((Client2ManagementRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Client2ManagementRequest other) {
                if (other == Client2ManagementRequest.getDefaultInstance())
                    return this;
                if (other.hasAllHomePageImgInfo()) {
                    bitField0_ |= 0x00000001;
                    allHomePageImgInfo_ = other.allHomePageImgInfo_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasAllHomePageImgInfo()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Client2ManagementRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Client2ManagementRequest) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required string AllHomePageImgInfo = 1;</code>
             * <p/>
             * <pre>
             * 固定字符串
             * </pre>
             */
            public boolean hasAllHomePageImgInfo() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string AllHomePageImgInfo = 1;</code>
             * <p/>
             * <pre>
             * 固定字符串
             * </pre>
             */
            public String getAllHomePageImgInfo() {
                Object ref = allHomePageImgInfo_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    allHomePageImgInfo_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string AllHomePageImgInfo = 1;</code>
             * <p/>
             * <pre>
             * 固定字符串
             * </pre>
             */
            public Builder setAllHomePageImgInfo(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                allHomePageImgInfo_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string AllHomePageImgInfo = 1;</code>
             * <p/>
             * <pre>
             * 固定字符串
             * </pre>
             */
            public com.google.protobuf.ByteString
            getAllHomePageImgInfoBytes() {
                Object ref = allHomePageImgInfo_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    allHomePageImgInfo_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string AllHomePageImgInfo = 1;</code>
             * <p/>
             * <pre>
             * 固定字符串
             * </pre>
             */
            public Builder setAllHomePageImgInfoBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                allHomePageImgInfo_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string AllHomePageImgInfo = 1;</code>
             * <p/>
             * <pre>
             * 固定字符串
             * </pre>
             */
            public Builder clearAllHomePageImgInfo() {
                bitField0_ = (bitField0_ & ~0x00000001);
                allHomePageImgInfo_ = getDefaultInstance().getAllHomePageImgInfo();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Client2ManagementRequest)
        }

        static {
            defaultInstance = new Client2ManagementRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:Client2ManagementRequest)
    }

    /**
     * Protobuf type {@code Client2ManagementResponse}
     */
    public static final class Client2ManagementResponse extends
            com.google.protobuf.GeneratedMessage
            implements Client2ManagementResponseOrBuilder {
        // required int32 result_code = 1;
        public static final int RESULT_CODE_FIELD_NUMBER = 1;
        // required string result_message = 2;
        public static final int RESULT_MESSAGE_FIELD_NUMBER = 2;
        private static final Client2ManagementResponse defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<Client2ManagementResponse> PARSER =
                new com.google.protobuf.AbstractParser<Client2ManagementResponse>() {
                    public Client2ManagementResponse parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Client2ManagementResponse(input, extensionRegistry);
                    }
                };
        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private int resultCode_;
        private Object resultMessage_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Client2ManagementResponse.newBuilder() to construct.
        private Client2ManagementResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Client2ManagementResponse(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Client2ManagementResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            resultCode_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            resultMessage_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static Client2ManagementResponse getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return HomePageImgInfo.internal_static_Client2ManagementResponse_descriptor;
        }

        public static Client2ManagementResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Client2ManagementResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Client2ManagementResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Client2ManagementResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Client2ManagementResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Client2ManagementResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Client2ManagementResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static Client2ManagementResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static Client2ManagementResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Client2ManagementResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(Client2ManagementResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Client2ManagementResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return HomePageImgInfo.internal_static_Client2ManagementResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Client2ManagementResponse.class, Builder.class);
        }

        @Override
        public com.google.protobuf.Parser<Client2ManagementResponse> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required int32 result_code = 1;</code>
         */
        public boolean hasResultCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int32 result_code = 1;</code>
         */
        public int getResultCode() {
            return resultCode_;
        }

        /**
         * <code>required string result_message = 2;</code>
         */
        public boolean hasResultMessage() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string result_message = 2;</code>
         */
        public String getResultMessage() {
            Object ref = resultMessage_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    resultMessage_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string result_message = 2;</code>
         */
        public com.google.protobuf.ByteString
        getResultMessageBytes() {
            Object ref = resultMessage_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                resultMessage_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            resultCode_ = 0;
            resultMessage_ = "";
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasResultCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasResultMessage()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, resultCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getResultMessageBytes());
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, resultCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getResultMessageBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Client2ManagementResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements Client2ManagementResponseOrBuilder {
            private int bitField0_;
            // required int32 result_code = 1;
            private int resultCode_;
            // required string result_message = 2;
            private Object resultMessage_ = "";

            // Construct using xinli.moho.protocol.HomePageImgInfo.Client2ManagementResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return HomePageImgInfo.internal_static_Client2ManagementResponse_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return HomePageImgInfo.internal_static_Client2ManagementResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Client2ManagementResponse.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                resultCode_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                resultMessage_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return HomePageImgInfo.internal_static_Client2ManagementResponse_descriptor;
            }

            public Client2ManagementResponse getDefaultInstanceForType() {
                return Client2ManagementResponse.getDefaultInstance();
            }

            public Client2ManagementResponse build() {
                Client2ManagementResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Client2ManagementResponse buildPartial() {
                Client2ManagementResponse result = new Client2ManagementResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.resultCode_ = resultCode_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.resultMessage_ = resultMessage_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Client2ManagementResponse) {
                    return mergeFrom((Client2ManagementResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Client2ManagementResponse other) {
                if (other == Client2ManagementResponse.getDefaultInstance())
                    return this;
                if (other.hasResultCode()) {
                    setResultCode(other.getResultCode());
                }
                if (other.hasResultMessage()) {
                    bitField0_ |= 0x00000002;
                    resultMessage_ = other.resultMessage_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasResultCode()) {

                    return false;
                }
                if (!hasResultMessage()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Client2ManagementResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Client2ManagementResponse) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required int32 result_code = 1;</code>
             */
            public boolean hasResultCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int32 result_code = 1;</code>
             */
            public int getResultCode() {
                return resultCode_;
            }

            /**
             * <code>required int32 result_code = 1;</code>
             */
            public Builder setResultCode(int value) {
                bitField0_ |= 0x00000001;
                resultCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 result_code = 1;</code>
             */
            public Builder clearResultCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                resultCode_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>required string result_message = 2;</code>
             */
            public boolean hasResultMessage() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string result_message = 2;</code>
             */
            public String getResultMessage() {
                Object ref = resultMessage_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    resultMessage_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string result_message = 2;</code>
             */
            public Builder setResultMessage(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                resultMessage_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string result_message = 2;</code>
             */
            public com.google.protobuf.ByteString
            getResultMessageBytes() {
                Object ref = resultMessage_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    resultMessage_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string result_message = 2;</code>
             */
            public Builder setResultMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                resultMessage_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string result_message = 2;</code>
             */
            public Builder clearResultMessage() {
                bitField0_ = (bitField0_ & ~0x00000002);
                resultMessage_ = getDefaultInstance().getResultMessage();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Client2ManagementResponse)
        }

        static {
            defaultInstance = new Client2ManagementResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:Client2ManagementResponse)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
